import type { ReactNode } from "react";

const STEPS = [
  {
    n: "01",
    t: "Ingest two sources",
    d: "The books ledger (what the merchant thinks happened) and the rail's settlement file (what actually paid). 66 rows each, integer paise, deterministic seed — every number on this console regenerates bit-for-bit.",
    code: "generate(seed=42)",
  },
  {
    n: "02",
    t: "Match deterministically",
    d: "Exact key match with graded checks: order refs pair up, fees must match the published schedule, net must reconcile with gross − fee, currencies must agree, settle lag must sit inside the T+1 SLA. No LLM in this path — matching is arithmetic.",
    code: "match(books, settlements)",
  },
  {
    n: "03",
    t: "Diagnose each break",
    d: "Unmatched rows are classified into a six-class taxonomy — timing gap, amount drift, missing entry, duplicate charge, fee mismatch, currency mismatch — with severity and evidence derived from the records themselves. The LLM, when keyed, only annotates a labeled AI-suggested hint.",
    code: "diagnose(break)",
  },
  {
    n: "04",
    t: "Remediate by runbook",
    d: "Each class maps to a runbook (RBT-01…06) with hard stopping rules: ≥ ₹50,000 always pages a human, currency never auto-acts, max 5 auto-resolutions per batch, one automated action per incident, and the engine never writes to the books silently — proposals only.",
    code: "run_runbook(incident)",
  },
  {
    n: "05",
    t: "Page a human, record it",
    d: "Money-adjacent actions wait for you: approve or reject right on the incident. Every decision lands in the append-only event log as a human event — the audit trail is the story, not a promise.",
    code: "human_decide(id, 'approve')",
  },
  {
    n: "06",
    t: "Write the postmortem",
    d: "The batch closes with the SRE artifact: match rate, resolution rate, MTTR, the honest could-not-resolve list with reasons, and what we'd change next. Regenerated by make report — numbers enter the repo only through regeneration.",
    code: "write_postmortem(batch)",
  },
];

export function HowItWorks() {
  return (
    <div className="max-w-4xl">
      <div className="mb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-accent">
        the loop
      </div>
      <h1 className="mb-3 text-[28px] font-semibold tracking-[-0.02em]">
        Reconciliation, run like incident response
      </h1>
      <p className="mb-8 max-w-[64ch] text-[13.5px] leading-relaxed text-muted">
        Every ops team has an SRE: someone who watches the system, diagnoses what broke, follows
        a bounded runbook, and pages a human when the automation shouldn't decide. Finance teams
        close books by hand. SettleOps gives finance the SRE treatment — six steps, all
        deterministic, all auditable.
      </p>

      <div className="grid gap-3 md:grid-cols-2">
        {STEPS.map((s) => (
          <section key={s.n} className="card px-5 py-4">
            <div className="flex items-baseline justify-between">
              <h3 className="text-[15px] font-semibold">{s.t}</h3>
              <span className="font-mono text-[11px] text-faint">{s.n}</span>
            </div>
            <p className="mt-1.5 text-[13px] leading-relaxed text-muted">{s.d}</p>
            <div className="mt-3 rounded-md bg-paper px-2.5 py-1.5 font-mono text-[11.5px] text-ink">
              {s.code}
            </div>
          </section>
        ))}
      </div>

      <StoppingRules />
    </div>
  );
}

function StoppingRules() {
  const rules: [string, string, ReactNode][] = [
    ["S1", "≥ ₹50,000 pages a human", "no silent large-value auto-actions, any break class"],
    ["S2", "currency mismatch never auto-acts", "wrong-FX write-backs are unrecoverable; always SEV-1"],
    ["S3", "max 5 auto-resolutions per batch", "runaway automation stops itself; the rest escalate"],
    ["S4", "one automated action per incident", "and a rejected proposal is never re-proposed by a machine"],
    ["S5", "proposals only, never silent writes", "no journal adjustment lands without an approval event"],
  ];
  return (
    <section className="card mt-6 px-5 py-4">
      <h3 className="text-[11px] font-semibold uppercase tracking-[0.07em] text-faint">
        the five stopping rules — what makes it bounded
      </h3>
      <table className="mt-3 w-full text-left text-[13px]">
        <tbody>
          {rules.map(([id, rule, why]) => (
            <tr key={id} className="border-b border-line/70 last:border-b-0">
              <td className="w-16 py-2.5 font-mono text-[12px] font-semibold text-crit">{id}</td>
              <td className="py-2.5 pr-4 font-medium text-ink">{rule}</td>
              <td className="py-2.5 text-muted">{why}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="mt-3 text-[11.5px] text-faint">
        each rule has a dedicated test in <span className="font-mono">tests/test_engine.py</span> —
        they are enforced by the suite, not by prose
      </p>
    </section>
  );
}
